apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      imagePullSecrets:
        - name: dockerhub-secret   # Required if repo is private
      containers:
        - name: myweb
          image: jayesh776/myimage:BUILD_TAG  # <-- placeholder for Jenkins
          ports:
            - containerPort: 8080
